#!/bin/bash

gpuPath="$1"

echo "$gpuPath"

export LASSI_GPU_PATH="$gpuPath"

# Now, retain all arguments except first
shift

# we need to be on a machine with a GPU
ssh pmargani@vegas-hpc10 "${LASSI_GPU_PATH}/run_gpu_smooth" "$@"
