@startuml
node "GBT M&C" {

node LASSI {
[TLS Scanner] -right-> [DAQ]
[DAQ] -right-> [Post-Processing]
[TLS Scanner] -up-> [manager]
}


[DAQ] -up-> [manager]
[Post-Processing] -up-> [manager]
[manager] -right-> [Active Surface]

[Receivers]
[Instrumentation]
[Servos]
["..."]
}
@enduml
